spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/v1/recommendations/**
        
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/v1/activities/**

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
