#spring.application.name=configserver

server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sandeepborkar94/microservices-with-ai.git
          default-label: master  # or whatever branch you’re using
          search-paths:
            - .
